### ISSUE TITLE
Potential caching issue with variables over time

### ISSUE THREAD

**Issue by jmarnold** [DovetailSoftware/dovetail-bootstrap#38]
Observed in Focus:

```
2017-11-22 09:59:41,787 [22] ERROR Agent.Core.Configuration.UnhandledExceptionLoggingBehavior - (null) A route /agent/support/cases/16207?_=1511366386982 caused an exception that was not handled. 
System.NullReferenceException: Object reference not set to an instance of an object.
   at FChoice.Foundation.FCSession.get_UserName()
   at Dovetail.SDK.ModelMap.SdkUserNameVariable.Expand(VariableExpansionContext context)
   at Dovetail.SDK.ModelMap.Serialization.XElementSerializer.Deserialize[T](XElement element)
   at Dovetail.SDK.ModelMap.Serialization.AddArgument.Visit(XElement element, ModelMap map, ParsingContext context)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.<>c__DisplayClass3.<Visit>b__1(IElementVisitor visitor)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.XElementService.Visit(XElement element, ModelMap map, ParsingContext context)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.Serialization.ModelMapParser.parse(ModelMap map, XDocument document, ModelMapCompilationReport report)
   at Dovetail.SDK.ModelMap.Serialization.ModelMapParser.Parse(ModelMap map, String filePath)
   at Dovetail.SDK.ModelMap.Serialization.Overrides.ModelMapOverrideParser.Parse(ModelMap map, String filePath)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at System.Collections.Generic.GenericEnumerableExtensions.Each[T](IEnumerable`1 values, Action`1 eachAction)
   at Dovetail.SDK.ModelMap.ModelMapCache.findMaps(String include)
   at System.Lazy`1.CreateValue()
```

This happened with ALL maps.
Caching was disabled at the time.

**Comment by jmarnold** [comment]
Should be addressed with this: https://github.com/DovetailSoftware/dovetail-bootstrap/pull/39
